#!/bin/bash
# Dumps container into file

# dumpimage <container-id/container-name>

if [[ -z "${1}" ]]; then
    >&2 echo "Please input container name/id"
    exit 1
fi

docker container export ${1} -o "${1}.tar"
