#!/bin/bash
# Prints container information in JSON
# -a    inspects image

container=$(docker ps --all --format '{{.ID}}')

if [[ -z "$container" ]]; then
    echo -n "[]"
    exit 0
fi

if [[ ${1} == "-a" ]]; then
    info="$(docker inspect --type container $container)"
    echo -n $info
elif [[ ! -z ${1} ]]; then
    info="$(docker inspect --type container ${1})"
    echo -n $info
else
    id="$(printf '"%s",' $container)"
    echo -n "[${id::${#id}-1}]"
fi
