#!/bin/bash
# Prints network information in JSON

# listnetwork [ -a / network-id ] [...network-id]

network=$(docker network ls --quiet)

if [[ -z "$network" ]]; then
    echo "[]"
    exit 0
fi

if [[ ${1} == "-a" ]]; then
    info="$(docker inspect --type network $network)"
    echo $inf | jq -c --monochrome-output
elif [[ ! -z ${1} ]]; then
    info="$(docker inspect --type network ${@})"
    echo $info | jq -c --monochrome-output
else
    id="$(printf '"%s",' $network)"
    echo "[${id::${#id}-1}]" | jq -c --monochrome-output
fi
