#!/bin/bash
# Prints volume information in JSON

# listvolume [ -a / volume-id ] [...volume-id]

volume=$(docker volume ls --quiet)

if [[ -z "$volume" ]]; then
    echo -n "[]"
    exit 0
fi

if [[ ${1} == "-a" ]]; then
    info="$(docker inspect --type volume $volume)"
    echo -n $info
elif [[ ! -z ${1} ]]; then
    info="$(docker inspect --type volume ${@})"
    echo -n $info
else
    id="$(printf '"%s",' $volume)"
    echo -n "[${id::${#id}-1}]"
fi
