#!/bin/bash
# Prints image information in JSON
# -a    inspects image

images=$(docker image ls --all --format '{{.ID}}')

if [[ -z "$images" ]]; then
    echo -n "[]"
    exit 0
fi

if [[ ${1} == "-a" ]]; then
    info="$(docker inspect --type image $images)"
    echo -n $info
elif [[ ! -z ${1} ]]; then
    info="$(docker inspect --type image ${1})"
    echo -n $info
else
    id="$(printf '"%s",' $images)"
    echo -n "[${id::${#id}-1}]"
fi
