#!/bin/bash
# Prints image information in JSON

# listimage [ -a / image-id ] [...image-id]

images=$(docker image ls --all --quiet)

if [[ -z "$images" ]]; then
    echo -n "[]"
    exit 0
fi

if [[ ${1} == "-a" ]]; then
    info="$(docker inspect --type image $images)"
    echo -n $info
elif [[ ! -z ${1} ]]; then
    info="$(docker inspect --type image ${@})"
    echo -n $info
else
    id="$(printf '"%s",' $images)"
    echo -n "[${id::${#id}-1}]"
fi
