#!/bin/bash
# Prints container information in JSON

# listcontainer [ -a / container-id ] [...container-id]

container=$(docker ps --all --quiet)

if [[ -z "$container" ]]; then
    echo -n "[]"
    exit 0
fi

if [[ ${1} == "-a" ]]; then
    info="$(docker inspect --type container $container)"
    echo -n $info
elif [[ ! -z ${1} ]]; then
    info="$(docker inspect --type container ${@})"
    echo -n $info
else
    id="$(printf '"%s",' $container)"
    echo -n "[${id::${#id}-1}]"
fi
