version: "3.9"

services:
  acquisition:
    build: ./acquisition
    container_name: acquisition
    environment:
      - DOCKER_HOST=${VM_SOCKET}
    restart: always
    networks:
      - acquire

  restapi:
    build: ./middleware
    container_name: restapi
    restart: always
    networks:
      - acquire
      - db
    volumes:
      - "./middleware/dockerdata:/opt/restapi/dockerdata:rw"
    ports:
      - "3000:3000"

  database:
    image: mongo
    container_name: database
    restart: always
    networks:
      - db
    volumes:
      - ketos-db-volume:/data/db:rw

volumes:
  ketos-db-volume:
    external: false

networks:
  db:
    name: ketos_db_local
  acquire:
    name: ketos_acquire_local
