version: "3.9"

services:
  acquisition:
    build: ./acquisition
    container_name: acquisition
    environment:
      - DOCKER_HOST=${VM_SOCKET}
    restart: always
    networks:
      - acquire

  restapi:
    build: ./middleware
    container_name: restapi
    restart: always
    networks:
      - acquire
      - api
    volumes:
      - "./middleware/dockerdata:/opt/restapi/dockerdata:rw"

  database:
    image: mongo
    container_name: database
    restart: always
    networks:
      - api
    volumes:
      - "./middleware/dbdata:/data/db:rw"

networks:
  api:
    name: api_local
  acquire:
    name: acquire_local
