version: "3.9"

services:
  database:
    image: mongo
    container_name: database
    restart: always
    ports:
      - "27017:27017"
    networks:
      - api
    volumes:
      - "./middleware/dbdata:/data/db:rw"

networks:
  api:
    name: api_local
