#!/bin/bash
# Dumps image into file

# dumpimage <image-id/image-name>

if [[ -z "${1}" ]]; then
    >&2 echo "Please input image name/id"
    exit 1
fi

out="${1}.tar.gz"

if [[ ! -z "${2}" ]]; then
    out="${2}"
fi

docker image save ${1} | gzip --fast > $out
