#!/usr/bin/python3
# Parse layers into Dockerfile

# getdockerfile <image-id>

import json
import subprocess
import sys
import os


def main():
    if len(sys.argv) != 2:
        print("Please input Image ID", file=sys.stderr)
        sys.exit(1)

    image_id = sys.argv[1]

    out, err = subprocess.Popen(
        ["docker image history --no-trunc --format '{{json .}}' " + image_id],
        env=os.environ.copy(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        shell=True).communicate()

    if err:
        print(err.decode(), file=sys.stderr)
        sys.exit(1)

    out = out.decode().strip()
    out = out.split("\n")

    layers = []
    for layer in out:
        layer = json.loads(layer)["CreatedBy"]

        layer = layer.replace("/bin/sh -c #(nop) ", "").strip()
        layer = layer.replace("/bin/sh -c set -ex;", "RUN").strip()
        layer = layer.replace("/bin/sh -c set -eux;", "RUN").strip()

        layers.append(layer)

    layers = layers[::-1]

    final = {
        "Id": image_id,
        "layers": layers
    }
    print(json.dumps(final))


if __name__ == '__main__':
    main()
