#!/usr/bin/python3
# Prints container filesystem in JSON

# getfilesystem [ container.tar.gz ]
import json
import sys
import subprocess
import os

if len(sys.argv) != 2:
    print("Please input container tar.gz", file=sys.stderr)

container_fs = sys.argv[1]

out, err = subprocess.Popen(
    ["tar", "-tzf", container_fs],
    env=os.environ.copy(),
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
).communicate()

out = out.decode().strip()

filesystem = out.split("\n")

print(json.dumps(filesystem, separators=(",", ":")))
