#!/bin/bash
# Get layer information and dump into JSON

# getlayers <image-tarfile>

if [[ -z "${1}" ]]; then
    >&2 echo "Please input image tarfile path"
    exit 1
fi

binary="$(dirname $0)/../bin/dive"

if [[ "$(uname -s)" == "Darwin" ]]; then
    binary="${binary}/dive-macos_universal"
elif [[ "$(uname -m)" == "aarch64"  ]]; then
    binary="${binary}/dive-linux_arm64"
else
    binary="${binary}/dive-linux_amd64"
fi

$binary ${1} --source docker-archive -j "/tmp/$(basename ${1}).json" > /dev/null

jq -c --monochrome-output . /tmp/$(basename ${1}).json && rm /tmp/$(basename ${1}).json
