#!/usr/bin/python3

from flask import Flask, jsonify

import subprocess
import os
import json
import requests

API_URL = "http://restapi:3000/api"

app = Flask(__name__)


def error_msg():
    raise Exception("Something went wrong")


def run_cmd(cmd):
    out, err = subprocess.Popen(cmd,
                                env=os.environ.copy(),
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE).communicate()

    if err:
        return False

    return out.decode().strip()


def get_info(cmd):
    if not (out := run_cmd(cmd)):
        error_msg()

    return json.loads(out)


def send_info(url_path, data, identifier=True):
    for entry in data:
        if identifier:
            iden = entry["Id"]
        else:
            iden = entry["Name"]

        r = requests.post(f"{API_URL}{url_path}/{iden}", json=entry)
        if r.status_code != 200:
            error_msg()


def get_dockerfile(image_hashes):
    final = []
    for iden in image_hashes:
        dockerfile = run_cmd(["./helper/getdockerfile", iden])
        final.append(json.loads(dockerfile))

    return final


def send_dockerfile(url_path, image_hashes, data):
    for hashh, entry in zip(image_hashes, data):
        r = requests.post(f"{API_URL}{url_path}/{hashh}", json=entry)
        if r.status_code != 200:
            error_msg()


def get_image(image_hashes):
    for iden in image_hashes:
        run_cmd(["./helper/dumpimage", iden])


def get_container(container_hashes):
    for iden in container_hashes:
        run_cmd(["./helper/dumpcontainer", iden])


def send_file(url_path, image_path):
    r = requests.post(f"{API_URL}{url_path}", files={"file": open(image_path, 'rb')})
    if r.status_code != 200:
        error_msg()


def acquire_info():
    # Sending info
    image_info = get_info(["./helper/listimage", "-a"])
    send_info("/image/info/insert", image_info)

    container_info = get_info(["./helper/listcontainer", "-a"])
    send_info("/container/info/insert", container_info)

    volume_info = get_info(["./helper/listvolume", "-a"])
    send_info("/volume/info/insert", volume_info, False)

    network_info = get_info(["./helper/listnetwork", "-a"])
    send_info("/network/info/insert", network_info)

    # Send dockerfiles
    image_hashes = get_info(["./helper/listimage"])
    dockerfiles = get_dockerfile(image_hashes)
    send_dockerfile("/image/dockerfile/insert", image_hashes, dockerfiles)

    # Sending image dumps
    image_hashes = get_info(["./helper/listimage"])
    get_image(image_hashes)
    for hashh in image_hashes:
        send_file("/image/upload", f"{hashh}.tar.gz")
        os.unlink(f"{hashh}.tar.gz")

    # Sending container dumps
    container_hash = get_info(["./helper/listcontainer"])
    get_container(container_hash)
    for hashh in container_hash:
        send_file("/container/upload", f"{hashh}.tar.gz")
        os.unlink(f"{hashh}.tar.gz")


@app.route('/acquire', methods=['GET'])
def start():
    try:
        acquire_info()
        return jsonify({"response": True})
    except:
        return jsonify({"response": False})


if __name__ == '__main__':
    app.run(host="0.0.0.0")
